import './globals.css';
import type { Metadata } from 'next';
import { Roboto_Serif } from 'next/font/google';
import NavLinks from '@/components/NavLinks';
import Footer from '@/components/Footer';

const roboto = Roboto_Serif({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'The Movie Watcher',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <header>
          <NavLinks />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
