import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import Nothing from "@/components/Nothing";

const bodyfont = Montserrat({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "The Movie Watcher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang='en'>
        <body className={bodyfont.className}>
          <header>
            <Navbar />
            <Nothing />
          </header>
          <main> {children}</main>
          <footer>
            <Footer />
          </footer>
        </body>
      </html>
  );
}
